export const sampleData = [
    { user_name: 'admin', group: 'Administrators' },
    { user_name: 'EINANIR', group: 'IT Edirne' },
    { user_name: 'EEDIZ', group: 'IT Edirne' },
    { user_name: 'MHADIMLIOGLU', group: 'MBT_IST_BP_BY' },
    { user_name: 'BDEMIR', group: 'MBT_IST_BP_BY' },
    { user_name: 'STKBAYRAM', group: 'MBT_IST_BP_BY' },
    { user_name: 'MTEKTEN', group: 'MBT_IST_BP_BY' },
    { user_name: 'ELASLAN', group: 'MBT_IST_BP_BY' },
    { user_name: 'admin', group: 'MBT_IST_BP_MY' },
    { user_name: 'admin', group: 'MBT_AKS_BP_BY' },
    { user_name: 'admin', group: 'MBT_AKS_BP_MY' },
    { user_name: 'EEDIZ', group: 'MBT_IST_YON' },
    { user_name: 'EEDIZ', group: 'MBT_IST_OZL_BRD' },
    { user_name: 'STKBAYRAM', group: 'MBT_IST_OZL_BRD' },
    { user_name: 'Elifffff5', group: 'MBT_IST_OZL_BRD' },
    { user_name: 'MHADIMLIOGLU', group: 'asa' },
    { user_name: 'ufuk', group: 'UFUKDRUP' },
];
